package pe.bn.com.mwbm.transversal.util.constantes;

import java.util.HashMap;
import java.util.Map;

public class ConstantesSeguridad {

	/* ACCESOS DE CONSULTA */
	public static String ACCESO_CONSULTAS = "ACCESO_CONSULTAS";
	public static String ACCESO_CONSULTA_OPERACIONES_REALIZADAS = "ACCESO_CONSULTA_OPERACIONES_REALIZADAS";
	public static String ACCESO_CONSULTA_OPERACIONES_PRESTAMOS = "ACCESO_CONSULTA_OPERACIONES_PRESTAMOS";
	public static String ACCESO_CONSULTAR_AFILIACION = "ACCESO_CONSULTA_AFILIACION";
	public static String ACCESO_CONSULTA_RESUMENES_OPERATIVOS = "ACCESO_CONSULTA_RESUMENES_OPERATIVOS";
	public static String ACCESO_CONSULTA_ACTIVIDADES_USUARIO = "ACCESO_CONSULTA_ACTIVIDADES_USUARIO";
	public static String ACCESO_CONSULTA_CLAVE_SMS_GENERADAS = "ACCESO_CONSULTA_CLAVE_SMS_GENERADAS";
	public static String ACCESO_CONSULTA_CLIENTES_AFILIADOS = "ACCESO_CONSULTA_CLIENTES_AFILIADOS";
	public static String ACCESO_CONSULTA_OPERACIONES_CANAL = "ACCESO_CONSULTA_OPERACIONES_CANAL";
	public static String ACCESO_CONSULTA_CLAVE_SMS_ACTIVOS_CANAL = "ACCESO_CONSULTA_CLAVE_SMS_ACTIVOS_CANAL";
	public static String ACCESO_CONSULTA_OPERACIONES_MULTIRED_VIRTUAL = "ACCESO_CONSULTA_OPERACIONES_MULTIRED_VIRTUAL";
	public static String ACCESO_CONSULTA_SELLO_SEGURIDAD = "ACCESO_CONSULTA_SELLO_SEGURIDAD";
	public static String ACCESO_CONSULTA_MENSAJES_SATI = "ACCESO_CONSULTA_MENSAJES_SATI";
	public static String ACCESO_CONSULTA_TRANSACCION = "ACCESO_CONSULTA_TRANSACCION";
	public static String ACCESO_CONSOLIDADO_TRANSACCION = "ACCESO_CONSOLIDADO_TRANSACCION";
	public static String ACCESO_CONSULTA_ARCHIVO_DIARIO = "ACCESO_CONSULTA_ARCHIVO_DIARIO";
	public static String ACCESO_CONSULTA_REGISTRO_AFILIACION = "ACCESO_CONSULTA_REGISTRO_AFILIACION";
	public static String ACCESO_CONSULTA_IP_NO_PERMITIDA = "ACCESO_CONSULTA_IP_NO_PERMITIDA";
	
	public static String ACCESO_CONSULTA_GENERACION_CLAVE_SEIS = "ACCESO_CONSULTA_CLAVE_SEIS";
	

	/* ACCESOS DE MANTENIMIENTO */
	public static String ACCESO_MANTENIMIENTO = "ACCESO_MANTENIMIENTO";
	public static String ACCESO_MANTENIMIENTO_PARAMETROS = "ACCESO_MANTENIMIENTO_PARAMETROS";
	public static String ACCESO_MANTENIMIENTO_MENSAJES = "ACCESO_MANTENIMIENTO_MENSAJES";
	public static String ACCESO_MANTENIMIENTO_LIMITES = "ACCESO_MANTENIMIENTO_LIMITES";
	public static String ACCESO_MANTENIMIENTO_FLAG_RECARGA = "ACCESO_MANTENIMIENTO_FLAG_RECARGA";
	public static String ACCESO_MANTENIMIENTO_TRANSFERENCIA_IB_INMEDIATA = "ACCESO_MANTENIMIENTO_TRANSFERENCIA_IB_INMEDIATA";
	public static String ACCESO_MANTENIMIENTO_PAGO_TC_INMEDIATA = "ACCESO_MANTENIMIENTO_PAGO_TC_INMEDIATA";
	public static String ACCESO_MANTENIMIENTO_CORREOS_INVALIDO = "ACCESO_MANTENIMIENTO_CORREOS_INVALIDO";
	public static String ACCESO_MANTENIMIENTO_FERIADOS = "ACCESO_MANTENIMIENTO_FERIADOS";
	public static String ACCESO_MANTENIMIENTO_TRANSFERENCIA_IB_DIFERIDA = "ACCESO_MANTENIMIENTO_TRANSFERENCIA_IB_DIFERIDA";
	public static String ACCESO_MANTENIMIENTO_PAGO_TC_DIFERIDA = "ACCESO_MANTENIMIENTO_PAGO_TC_DIFERIDA";
	public static String ACCESO_MANTENIMIENTO__VALIDACION_IP = "ACCESO_MANTENIMIENTO_VALIDACION_IP";
	/**/

	/* ACCESOS DE GESTION INVITACIONES */
	public static String ACCESO_GESTION_INVITACIONES = "ACCESO_GESTION_INVITACIONES";
	public static String ACCESO_GESTION_BANDEJA_INVITACIONES = "ACCESO_GESTION_BANDEJA_INVITACIONES";
	
	
	
	public final static Map<String, String> OPCION_ACC = new HashMap<String, String>() {
		private static final long serialVersionUID = 1L;

		{					 			

			put("01S", ACCESO_CONSULTAS);
			put("02S", ACCESO_CONSULTA_OPERACIONES_REALIZADAS);
			put("03S", ACCESO_CONSULTA_OPERACIONES_PRESTAMOS);
			put("04S", ACCESO_CONSULTA_RESUMENES_OPERATIVOS);
			put("05S", ACCESO_CONSULTAR_AFILIACION);
			put("06S", ACCESO_CONSULTA_ACTIVIDADES_USUARIO);
			
			put("07S", ACCESO_MANTENIMIENTO_PARAMETROS);
			
			put("17S", ACCESO_CONSULTA_CLAVE_SMS_GENERADAS);
			put("18S", ACCESO_CONSULTA_CLIENTES_AFILIADOS);
			put("19S", ACCESO_CONSULTA_CLAVE_SMS_ACTIVOS_CANAL);	
			put("20S", ACCESO_GESTION_INVITACIONES);
			put("21S", ACCESO_GESTION_BANDEJA_INVITACIONES);
			put("22S", ACCESO_CONSULTA_OPERACIONES_CANAL);
			
			put("23S", ACCESO_CONSULTA_OPERACIONES_MULTIRED_VIRTUAL);
			
			put("24S", ACCESO_CONSULTA_TRANSACCION);
			
			put("25S", ACCESO_CONSOLIDADO_TRANSACCION);
			
			put("26S", ACCESO_CONSULTA_SELLO_SEGURIDAD);
			put("08S", ACCESO_CONSULTA_MENSAJES_SATI);
			put("09S", ACCESO_MANTENIMIENTO__VALIDACION_IP);
			put("10S", ACCESO_CONSULTA_REGISTRO_AFILIACION);
			put("11S", ACCESO_CONSULTA_ARCHIVO_DIARIO);
			put("12S", ACCESO_CONSULTA_IP_NO_PERMITIDA);
			
			//generacion de clave 6
			put("27S", ACCESO_CONSULTA_GENERACION_CLAVE_SEIS);
			
		}
	};
	

	public final static Map<String, String> OPCION_ACCM = new HashMap<String, String>() {
		private static final long serialVersionUID = 1L;
		{		
			put("08S", ACCESO_MANTENIMIENTO_MENSAJES);
			put("09S", ACCESO_MANTENIMIENTO_LIMITES);
			put("10S", ACCESO_MANTENIMIENTO_FLAG_RECARGA);
			put("11S", ACCESO_MANTENIMIENTO_TRANSFERENCIA_IB_INMEDIATA);
			put("12S", ACCESO_MANTENIMIENTO_PAGO_TC_INMEDIATA);
			put("13S", ACCESO_MANTENIMIENTO_CORREOS_INVALIDO);
			put("14S", ACCESO_MANTENIMIENTO_FERIADOS);
			put("15S", ACCESO_MANTENIMIENTO_TRANSFERENCIA_IB_DIFERIDA);
			put("16S", ACCESO_MANTENIMIENTO_PAGO_TC_DIFERIDA);
		}
	};

}