//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.bn.com.mwbm.transversal.ws.comp.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pe.com.bn.comp.ws.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pe.com.bn.comp.ws.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatoParametroService }
     * 
     */
    public DatoParametroService createDatoParametroService() {
        return new DatoParametroService();
    }

    /**
     * Create an instance of {@link DatoParametroServiceResponse }
     * 
     */
    public DatoParametroServiceResponse createDatoParametroServiceResponse() {
        return new DatoParametroServiceResponse();
    }

    /**
     * Create an instance of {@link ArrayOfTns2NillableParametro }
     * 
     */
    public ArrayOfTns2NillableParametro createArrayOfTns2NillableParametro() {
        return new ArrayOfTns2NillableParametro();
    }

    /**
     * Create an instance of {@link ArrayOfTns2NillableGrupoParametro }
     * 
     */
    public ArrayOfTns2NillableGrupoParametro createArrayOfTns2NillableGrupoParametro() {
        return new ArrayOfTns2NillableGrupoParametro();
    }

}
