//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.bn.com.mwbm.transversal.ws.comp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import pe.bn.com.mwbm.transversal.ws.comp.bean.SistemaParametro;

@WebService(name = "ParametroInterfazKey", targetNamespace = "http://service.ws.comp.bn.com.pe")
@XmlSeeAlso({
    pe.bn.com.mwbm.transversal.ws.comp.bean.ObjectFactory.class,
    pe.bn.com.mwbm.transversal.ws.comp.service.ObjectFactory.class
})
public interface ParametroInterfazKey {


    /**
     * 
     * @param sistema
     * @param idUsuario
     * @param semilla
     * @param llave
     * @param cuenta
     * @return
     *     returns pe.com.bn.comp.ws.bean.SistemaParametro
     */
    @WebMethod(action = "datoParametroService")
    @WebResult(name = "datoParametroServiceReturn", targetNamespace = "")
    @RequestWrapper(localName = "datoParametroService", targetNamespace = "http://service.ws.comp.bn.com.pe", className = "pe.com.bn.comp.ws.service.DatoParametroService")
    @ResponseWrapper(localName = "datoParametroServiceResponse", targetNamespace = "http://service.ws.comp.bn.com.pe", className = "pe.com.bn.comp.ws.service.DatoParametroServiceResponse")
    public SistemaParametro datoParametroService(
        @WebParam(name = "sistema", targetNamespace = "")
        String sistema,
        @WebParam(name = "cuenta", targetNamespace = "")
        String cuenta,
        @WebParam(name = "semilla", targetNamespace = "")
        String semilla,
        @WebParam(name = "llave", targetNamespace = "")
        byte[] llave,
        @WebParam(name = "idUsuario", targetNamespace = "")
        String idUsuario);

}
