//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.bn.com.mwbm.transversal.ws.comp.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import pe.bn.com.mwbm.transversal.ws.comp.service.ArrayOfTns2NillableParametro;


/**
 * <p>Java class for GrupoParametro complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrupoParametro">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoGrupo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aliasDescripGrupo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aliasGrupo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parametro" type="{http://service.ws.comp.bn.com.pe}ArrayOf_tns2_nillable_Parametro"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrupoParametro", propOrder = {
    "tipoGrupo",
    "aliasDescripGrupo",
    "aliasGrupo",
    "parametro"
})
public class GrupoParametro {

    @XmlElement(required = true, nillable = true)
    protected String tipoGrupo;
    @XmlElement(required = true, nillable = true)
    protected String aliasDescripGrupo;
    @XmlElement(required = true, nillable = true)
    protected String aliasGrupo;
    @XmlElement(required = true, nillable = true)
    protected ArrayOfTns2NillableParametro parametro;

    /**
     * Gets the value of the tipoGrupo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoGrupo() {
        return tipoGrupo;
    }

    /**
     * Sets the value of the tipoGrupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoGrupo(String value) {
        this.tipoGrupo = value;
    }

    /**
     * Gets the value of the aliasDescripGrupo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasDescripGrupo() {
        return aliasDescripGrupo;
    }

    /**
     * Sets the value of the aliasDescripGrupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasDescripGrupo(String value) {
        this.aliasDescripGrupo = value;
    }

    /**
     * Gets the value of the aliasGrupo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasGrupo() {
        return aliasGrupo;
    }

    /**
     * Sets the value of the aliasGrupo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasGrupo(String value) {
        this.aliasGrupo = value;
    }

    /**
     * Gets the value of the parametro property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTns2NillableParametro }
     *     
     */
    public ArrayOfTns2NillableParametro getParametro() {
        return parametro;
    }

    /**
     * Sets the value of the parametro property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTns2NillableParametro }
     *     
     */
    public void setParametro(ArrayOfTns2NillableParametro value) {
        this.parametro = value;
    }

}
