//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.bn.com.mwbm.transversal.ws.comp.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pe.com.bn.comp.ws.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pe.com.bn.comp.ws.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SistemaParametro }
     * 
     */
    public SistemaParametro createSistemaParametro() {
        return new SistemaParametro();
    }

    /**
     * Create an instance of {@link Parametro }
     * 
     */
    public Parametro createParametro() {
        return new Parametro();
    }

    /**
     * Create an instance of {@link ReturnProceso }
     * 
     */
    public ReturnProceso createReturnProceso() {
        return new ReturnProceso();
    }

    /**
     * Create an instance of {@link GrupoParametro }
     * 
     */
    public GrupoParametro createGrupoParametro() {
        return new GrupoParametro();
    }

}
